#!/usr/bin/env bash
# Function to display DNS information for a given subdomain

display_dns_info() {
    local subdomain="$1"
    local domain="$2"

    dig_output=$(dig "${subdomain}.${domain}" | awk '/^;; ANSWER SECTION:$/,/^$/' | awk '/IN\s+A/')

    if [[ -n "$dig_output" ]]; then
        destination=$(echo "$dig_output" | awk '{print $NF}')
        record_type=$(echo "$dig_output" | awk '{print $4}')
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    else
        echo "The subdomain $subdomain does not exist"
    fi
}

# Main script starts here
if [ "$#" -eq 1 ]; then
    domain="$1"
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        display_dns_info "$subdomain" "$domain"
    done
elif [ "$#" -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    display_dns_info "$subdomain" "$domain"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
