#!/usr/bin/env bash
# Function to display DNS information for a given subdomain

display_dns_info() {
    local subdomain="$1"
    local domain="$2"

    destination=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/ {getline; print $5}')
    record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/ {getline; print $4}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script starts here
if [ -z $2 ]; then
    domain="$1"
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        display_dns_info "$subdomain" "$domain"
    done
elif [ "$#" -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    display_dns_info "$subdomain" "$domain"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
