#!/usr/bin/env bash
# transfers a file from our client to a server

args=("$@")
if [ ${#args[@]} -lt 3 ]; then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
	exit 1
fi
scp -o StrictHostKeyChecking=no -i "${args[4]}" "${args[1]}" "${args[3]}@${args[2]}":~/
