#!/usr/bin/env bash
# install nginx

sudo apt-get -y updatex
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
kill -HUP $(pgrep nginx)

# Verify if Nginx is listening on port 80
netstat -tuln | grep ":80" > /dev/null
