#!/usr/bin/env bash
# Update package lists and install Nginx

apt-get -y update
apt-get -y install nginx

# Define the custom header configuration
HOST_NAME=$(hostname)
HEADER="\\\n\tadd_header X-Served-By $HOST_NAME;\n"

# Add the custom header to Nginx configuration
FIND=$(grep "add_header X-Served-By" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
    sed -i "/server_name _;/a $HEADER" /etc/nginx/sites-available/default
fi

# Create the index.html page with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Add redirection to another page in the Nginx configuration
FIND=$(grep "location /redirect_me" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
    STRING="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;\n\t}\n"
    sed -i "/server_name _;/a $STRING" /etc/nginx/sites-available/default
fi

# Add custom error page 404 configuration to Nginx
FIND=$(grep "error_page 404 /custom_404.html;" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
    ERROR="\\\n\terror_page 404 /custom_404.html;\n"
    echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
    sed -i "/server_name _;/a $ERROR" /etc/nginx/sites-available/default
fi

# Restart Nginx to apply the changes
service nginx restart
