#!/usr/bin/env bash
# Update package index

sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
echo '
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 477100-web-01 35.175.134.192:80 check
    server 477100-web-02 34.207.63.125:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply changes
service haproxy restart
