#!/usr/bin/env bash
# Update package index

sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 477100-web-01 35.175.134.192:80 check
    server 477100-web-02 34.207.63.125:80 check
EOF

# Restart HAProxy to apply changes
sudo systemctl restart haproxy

# Enable HAProxy init script
sudo systemctl enable haproxy

sed -i "s/\[477100\]/$(hostname | cut -d '-' -f 1)/g" /etc/haproxy/haproxy.cfg

# Restart HAProxy again to apply hostname changes
sudo systemctl restart haproxy
