#!/usr/bin/env bash
# use nginx user not root

# Step 1: Update NGINX configuration to run as nginx user
sed -i 's/user  nginx;/user nginx;/g' /etc/nginx/nginx.conf

# Step 2: Update NGINX configuration to listen on port 8080
sed -i 's/listen       80;/listen       8080;/g' /etc/nginx/nginx.conf

# Step 3: Restart NGINX service to apply changes
service nginx restart
